### PR TITLE
Fix discovering var statements inside functions.

### PR DESCRIPTION
**Pull request by elpete**

### CODE REVIEW

**Comment by elpete** [comment]
I'm still working out some kinks on this one.  Feel free to ask any questions if you have them.

**Comment by elpete** [comment]
That's better.  Let's go for that. 😄

**Comment by pfreitag** [comment]
Thanks for contributing @elpete it looks pretty good upon first glance, but I'll review it further before merging.

**Comment by elpete** [comment]
Hey, @pfreitag.  It's been a while since I opened this pull request.  Need anything from me to get it merged?

**Comment by pfreitag** [comment]
Hi @elpete thanks for following up -- the change looks good, I think the only thing currently is that the test script file:`tests/tests/templates/script/basic.cfc` had some stuff deleted in it - was there a reason for that?

**Comment by elpete** [comment]
I'm trying to remember (it's been a long time).  I think it was just that the `tests/templates/script/basic.cfc` was able to be changed without breaking tests, so I used it instead of creating another test. ¯\_(ツ)_/¯

**Comment by pfreitag** [comment]
Ok ... yup tests are still working... I'll go ahead and merge. Thanks @elpete

**Pull request merged**
